Repository php/pie, pull requests merged in 2024-12, with the labels that each got.

#147 Updated status of pcov ext
  docs/supported-extensions.md
Labels: documentation

#148 add remi's supported ext
  docs/supported-extensions.md
Labels: documentation

#122 feat: CI job for building Docker binary-only images
  .github/workflows/release.yml
  Dockerfile
  docs/usage.md
Labels: enhancement, maintainer feedback needed

#149 Add missing dependencies to composer.json
  composer.json
  composer.lock
Labels: enhancement

#116 Add support for `os-families-exclude` in extensions `composer.json`
  composer.lock
  src/DependencyResolver/IncompatibleOperatingSystemFamily.php
  src/DependencyResolver/Package.php
  src/DependencyResolver/ResolveDependencyWithComposer.php
  src/Platform/OperatingSystemFamily.php
  src/Platform/TargetPhp/PhpBinaryPath.php
  src/Platform/TargetPlatform.php
  test/integration/Building/UnixBuildTest.php
  test/integration/Downloading/GithubPackageReleaseAssetsTest.php
  test/integration/Installing/UnixInstallTest.php
  test/integration/Installing/WindowsInstallTest.php
  test/unit/Command/CommandHelperTest.php
  test/unit/ComposerIntegration/InstallAndBuildProcessTest.php
  test/unit/ComposerIntegration/InstalledJsonMetadataTest.php
  test/unit/ComposerIntegration/OverrideWindowsUrlInstallListenerTest.php
  test/unit/ComposerIntegration/VersionSelectorFactoryTest.php
  test/unit/DependencyResolver/IncompatibleOperatingSystemFamilyTest.php
  test/unit/DependencyResolver/PackageTest.php
  test/unit/DependencyResolver/ResolveDependencyWithComposerTest.php
  test/unit/Downloading/DownloadedPackageTest.php
  test/unit/Downloading/Exception/CouldNotFindReleaseAssetTest.php
  test/unit/Downloading/GithubPackageReleaseAssetsTest.php
  test/unit/Platform/OperatingSystemFamilyTest.php
  test/unit/Platform/TargetPhp/PhpBinaryPathTest.php
  test/unit/Platform/TargetPlatformTest.php
  test/unit/Platform/WindowsExtensionAssetNameTest.php
Labels: enhancement

#153 Fix conflict trying to install an ext that is already enabled
  src/ComposerIntegration/ComposerIntegrationHandler.php
  src/ComposerIntegration/PhpBinaryPathBasedPlatformRepository.php
  src/ComposerIntegration/PieComposerInstaller.php
  src/ComposerIntegration/VersionSelectorFactory.php
  test/unit/ComposerIntegration/PhpBinaryPathBasedPlatformRepositoryTest.php
Labels: bug

#154 Use Composer 2.8.4 and add warning to readme
  README.md
  composer.json
  composer.lock
Labels: enhancement

#158 Trim warnings and deprecations from output when invoking PHP in `PhpBinaryPath`
  features/install-extensions.feature
  src/Platform/TargetPhp/PhpBinaryPath.php
  test/behaviour/CliContext.php
Labels: bug

#159 Upgrade Behat and use PHP config
  behat.php
  behat.yml.dist
  composer.json
  composer.lock
Labels: enhancement

#155 Automatically setup php.ini entries
  src/Command/BuildCommand.php
  src/Command/CommandHelper.php
  src/Command/DownloadCommand.php
  src/Command/InfoCommand.php
  src/Command/InstallCommand.php
  src/ComposerIntegration/InstallAndBuildProcess.php
  src/ComposerIntegration/PieComposerRequest.php
  src/Container.php
  src/DependencyResolver/Package.php
  src/Installing/Ini/AddExtensionToTheIniFile.php
  src/Installing/Ini/CheckAndAddExtensionToIniIfNeeded.php
  src/Installing/Ini/DockerPhpExtEnable.php
  src/Installing/Ini/IsExtensionAlreadyInTheIniFile.php
  src/Installing/Ini/OndrejPhpenmod.php
  src/Installing/Ini/PickBestSetupIniApproach.php
  src/Installing/Ini/PreCheckExtensionAlreadyLoaded.php
  src/Installing/Ini/SetupIniApproach.php
  src/Installing/Ini/StandardAdditionalPhpIniDirectory.php
  src/Installing/Ini/StandardSinglePhpIni.php
  src/Installing/Install.php
  src/Installing/SetupIniFile.php
  src/Installing/UnixInstall.php
  src/Installing/WindowsInstall.php
  src/Platform/TargetPhp/Exception/ExtensionIsNotLoaded.php
  src/Platform/TargetPhp/PhpBinaryPath.php
  test/assets/docker-php-ext-enable/bad
  test/assets/docker-php-ext-enable/good
  test/assets/example_ini_files/with_commented_extension.ini
  test/assets/example_ini_files/with_extension.ini
  test/assets/example_ini_files/with_zend_extension.ini
  test/assets/example_ini_files/without_extension.ini
  test/assets/phpenmod/bad
  test/assets/phpenmod/good
  test/behaviour/CliContext.php
  test/integration/Building/UnixBuildTest.php
  test/integration/Command/InstallCommandTest.php
  test/integration/DependencyResolver/ResolveDependencyWithComposerTest.php
  test/integration/Downloading/GithubPackageReleaseAssetsTest.php
  test/integration/Installing/UnixInstallTest.php
  test/integration/Installing/WindowsInstallTest.php
  test/unit/Command/CommandHelperTest.php
  test/unit/ComposerIntegration/InstallAndBuildProcessTest.php
  test/unit/ComposerIntegration/InstalledJsonMetadataTest.php
  test/unit/ComposerIntegration/OverrideWindowsUrlInstallListenerTest.php
  test/unit/DependencyResolver/PackageTest.php
  test/unit/Downloading/DownloadedPackageTest.php
  test/unit/Downloading/Exception/CouldNotFindReleaseAssetTest.php
  test/unit/Downloading/GithubPackageReleaseAssetsTest.php
  test/unit/Installing/Ini/AddExtensionToTheIniFileTest.php
  test/unit/Installing/Ini/CheckAndAddExtensionToIniIfNeededTest.php
  test/unit/Installing/Ini/DockerPhpExtEnableTest.php
  test/unit/Installing/Ini/IsExtensionAlreadyInTheIniFileTest.php
  test/unit/Installing/Ini/OndrejPhpenmodTest.php
  test/unit/Installing/Ini/PickBestSetupIniApproachTest.php
  test/unit/Installing/Ini/PreCheckExtensionAlreadyLoadedTest.php
  test/unit/Installing/Ini/StandardAdditionalPhpIniDirectoryTest.php
  test/unit/Installing/Ini/StandardSinglePhpIniTest.php
  test/unit/Platform/TargetPhp/PhpBinaryPathTest.php
  test/unit/Platform/WindowsExtensionAssetNameTest.php
Labels: enhancement

#162 Sort supported extensions list alphabetically
  docs/supported-extensions.md
Labels: documentation

#163 Allow composer to ask for credentials
  src/ComposerIntegration/MinimalHelperSet.php
  src/ComposerIntegration/QuieterConsoleIO.php
  src/Container.php
  test/unit/ComposerIntegration/MinimalHelperSetTest.php
  test/unit/ComposerIntegration/QuieterConsoleIOTest.php
  test/unit/DependencyResolver/UnableToResolveRequirementTest.php
Labels: enhancement

#164 Enhance "show" command with PIE metadata
  src/Command/ShowCommand.php
  src/ComposerIntegration/PieComposerRequest.php
  src/ComposerIntegration/PieInstalledJsonMetadataKeys.php
  src/Platform/TargetPhp/PhpBinaryPath.php
  test/unit/ComposerIntegration/PieInstalledJsonMetadataKeysTest.php
Labels: enhancement

#165 Add support for the --force option
  src/Command/BuildCommand.php
  src/Command/CommandHelper.php
  src/Command/DownloadCommand.php
  src/Command/InfoCommand.php
  src/Command/InstallCommand.php
  src/ComposerIntegration/ComposerIntegrationHandler.php
  src/DependencyResolver/DependencyResolver.php
  src/DependencyResolver/ResolveDependencyWithComposer.php
  test/integration/Command/DownloadCommandTest.php
  test/integration/DependencyResolver/ResolveDependencyWithComposerTest.php
  test/unit/DependencyResolver/ResolveDependencyWithComposerTest.php
Labels: enhancement
