Repository php/pie, pull requests merged in 2024-11, with the labels that each got.

#90 Use Behat attributes instead of annotations
  test/behaviour/CliContext.php
Labels: enhancement

#91 Better authorization header handling in `AddAuthenticationHeader`
  src/Downloading/AddAuthenticationHeader.php
  test/unit/Downloading/AddAuthenticationHeaderTest.php
Labels: enhancement

#95 Use Composer HttpDownloader and remove Guzzle
  composer.json
  composer.lock
  src/ComposerIntegration/OverrideWindowsUrlInstallListener.php
  src/Container.php
  src/Downloading/AddAuthenticationHeader.php
  src/Downloading/AssertHttp.php
  src/Downloading/GithubPackageReleaseAssets.php
  src/Downloading/PackageReleaseAssets.php
  test/integration/Downloading/GithubPackageReleaseAssetsTest.php
  test/unit/Downloading/AddAuthenticationHeaderTest.php
  test/unit/Downloading/AssertHttpTest.php
  test/unit/Downloading/GithubPackageReleaseAssetsTest.php
Labels: enhancement

#103 Ensure built .so file matches the expected filename
  src/Building/ExtensionBinaryNotFound.php
  src/Building/UnixBuild.php
  test/integration/Building/UnixBuildTest.php
Labels: enhancement

#96 Add the `--with-phpize-path` option
  docs/usage.md
  src/Building/Build.php
  src/Building/UnixBuild.php
  src/Building/WindowsBuild.php
  src/Command/BuildCommand.php
  src/Command/CommandHelper.php
  src/Command/DownloadCommand.php
  src/Command/InfoCommand.php
  src/Command/InstallCommand.php
  src/ComposerIntegration/InstallAndBuildProcess.php
  src/ComposerIntegration/InstalledJsonMetadata.php
  src/ComposerIntegration/PieComposerRequest.php
  src/ComposerIntegration/PieInstalledJsonMetadataKeys.php
  src/Platform/TargetPhp/PhpizePath.php
  test/integration/Building/UnixBuildTest.php
  test/integration/DependencyResolver/ResolveDependencyWithComposerTest.php
  test/integration/Installing/UnixInstallTest.php
  test/unit/ComposerIntegration/InstallAndBuildProcessTest.php
  test/unit/ComposerIntegration/InstalledJsonMetadataTest.php
  test/unit/ComposerIntegration/OverrideWindowsUrlInstallListenerTest.php
  test/unit/Platform/TargetPlatformTest.php
Labels: enhancement

#104 Add new phpize path param missing from new test
  test/integration/Building/UnixBuildTest.php
Labels: bug

#114 Make all PHPUnit data providers static
  test/unit/ComposerIntegration/ComposerRunFailedTest.php
  test/unit/ComposerIntegration/QuieterConsoleIOTest.php
  test/unit/DependencyResolver/PackageTest.php
Labels: enhancement

#112 Use `#[RequiresOperatingSystemFamily]` where possible
  test/integration/Command/DownloadCommandTest.php
  test/integration/Command/InstallCommandTest.php
  test/integration/Installing/WindowsInstallTest.php
  test/unit/Command/CommandHelperTest.php
Labels: enhancement

#111 Prevent the `--with-phpize-path` option to be used on Windows
  src/Command/CommandHelper.php
  test/unit/Command/CommandHelperTest.php
Labels: enhancement

#119 Add Dependabot for GitHub Actions
  .github/dependabot.yml
Labels: enhancement

#115 Added support for build-path php-ext configuration
  composer.json
  composer.lock
  docs/extension-maintainers.md
  src/DependencyResolver/Package.php
  src/Downloading/DownloadedPackage.php
  test/integration/Building/UnixBuildTest.php
  test/integration/Downloading/GithubPackageReleaseAssetsTest.php
  test/integration/Installing/UnixInstallTest.php
  test/integration/Installing/WindowsInstallTest.php
  test/unit/Command/CommandHelperTest.php
  test/unit/DependencyResolver/PackageTest.php
  test/unit/Downloading/DownloadedPackageTest.php
  test/unit/Downloading/Exception/CouldNotFindReleaseAssetTest.php
  test/unit/Downloading/GithubPackageReleaseAssetsTest.php
  test/unit/Platform/WindowsExtensionAssetNameTest.php
Labels: enhancement

#121 Run `composer bump`
  composer.json
  composer.lock
Labels: enhancement

#123 Fix build phar job on forks that have no tags
  .github/workflows/release-unsigned-phar.yml
Labels: bug

#125 Enable Dependabot for composer
  .github/dependabot.yml
Labels: enhancement

#127 Configure fine-grained GitHub Action permissions
  .github/workflows/continuous-integration.yml
  .github/workflows/docs.yml
  .github/workflows/release-unsigned-phar.yml
  .github/workflows/release.yml
Labels: enhancement

#128 Add build provenance attestation to the release workflow
  .github/workflows/release.yml
Labels: enhancement

#131 chore: move the obtaining the version method to a separate class
  bin/pie
  src/Util/PieVersion.php
Labels: enhancement

#130 (feat) : Enhance UnixBuild with proper cleanup and improved test organization
  src/Building/UnixBuild.php
  test/integration/Building/UnixBuildTest.php
Labels: enhancement

#141 Update illuminate/container and illuminate/contracts
  composer.json
  composer.lock
Labels: bug

#139 Use GH attestation and organise workflows better
  .github/workflows/build-phar.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/docs.yml
  .github/workflows/release-unsigned-phar.yml
  .github/workflows/release.yml
  README.md
  docs/usage.md
Labels: enhancement

#142 Supported pecl extensions list
  docs/supported-extensions.md
Labels: documentation
