Repository php/pie, pull requests merged in 2025-02, with the labels that each got.

#182 Fix typo
  docs/usage.md
Labels: documentation

#188 Update and bump all the deps
  composer.json
  composer.lock
Labels: dependencies, php

#189 Mark inotify, memprof, rdkafka as supported
  docs/supported-extensions.md
Labels: documentation

#193 Allow old PEAR/PECL named convention packages for pre-packaged source
  src/Platform/PrePackagedSourceAssetName.php
  test/unit/Downloading/DownloadUrlMethodTest.php
  test/unit/Platform/PrePackagedSourceAssetNameTest.php
Labels: enhancement
