Repository php/pie, pull requests merged in 2025-05, with the labels that each got.

#227 Check for all exts required by a PHP project
  src/Command/InstallExtensionsForProjectCommand.php
  src/Installing/InstallForPhpProject/ComposerFactoryForProject.php
  src/Installing/InstallForPhpProject/DetermineExtensionsRequired.php
  src/Installing/InstallForPhpProject/FindRootPackage.php
  test/integration/Command/InstallExtensionsForProjectCommandTest.php
Labels: enhancement

#235 Create a GH issue when trusted root certs are outdated
  .github/workflows/check-outdated-trusted-root.yml
Labels: enhancement

#234 Fix self-update command issues
  box.json.dist
  src/Downloading/GithubPackageReleaseAssets.php
  src/SelfManage/Update/FetchPieReleaseFromGitHub.php
  src/SelfManage/Verify/FallbackVerificationUsingOpenSsl.php
  test/unit/SelfManage/Update/FetchPieReleaseFromGitHubTest.php
  test/unit/SelfManage/Verify/FallbackVerificationUsingOpenSslTest.php
Labels: bug

#233 Remove temporary phar when self-updating
  src/Command/SelfUpdateCommand.php
Labels: bug

#237 Add permissions for creating issues to trusted root cert check job
  .github/workflows/check-outdated-trusted-root.yml
Labels: bug

#246 Add mailparse
  docs/supported-extensions.md
Labels: documentation

#243 Documenting version constraint into pie.json
  docs/usage.md
Labels: documentation, enhancement

#245 Show command display PIE packages installed but not loaded in target PHP
  src/Command/ShowCommand.php
Labels: enhancement
