Repository php/pie, pull requests merged in 2025-08, with the labels that each got.

#318 Filter 'PHP ' prefixed notices from output
  src/Platform/TargetPhp/PhpBinaryPath.php
  test/assets/valid-php-with-warnings.sh
Labels: bug

#315 Silence deprecations
  bin/pie
Labels: dependencies

#319 Improve exception when using pre-packaged-source and a branch alias
  src/Downloading/Exception/CouldNotFindReleaseAsset.php
Labels: enhancement

#328 docs: add php-dev as dependency on Debian/Ubuntu systems
  README.md
Labels: documentation

#326 Check gh attestation command exists before using it
  src/SelfManage/Verify/GithubCliAttestationVerification.php
  src/SelfManage/Verify/GithubCliNotAvailable.php
  test/assets/fake-gh-cli/unhappy.bat
  test/assets/fake-gh-cli/unhappy.sh
Labels: bug

#331 Silence deprecations before vendor include
  bin/pie
Labels: dependencies
