Repository php/pie, pull requests merged in 2025-06, with the labels that each got.

#255 Run `composer bump`
  composer.json
  composer.lock
Labels: enhancement, dependencies

#257 Updated trusted root certificate
  resources/trusted-root.jsonl
Labels: enhancement

#270 Use version constraints for php project install
  src/Command/InstallExtensionsForProjectCommand.php
  src/Command/SelfUpdateCommand.php
  src/Command/SelfVerifyCommand.php
  src/Command/ShowCommand.php
  src/Container.php
  src/File/FullPathToSelf.php
  src/Installing/InstallForPhpProject/InstallSelectedPackage.php
  src/Installing/SetupIniFile.php
  src/SelfManage/Verify/FallbackVerificationUsingOpenSsl.php
  src/SelfManage/Verify/GithubCliAttestationVerification.php
  src/Util/Emoji.php
  test/integration/Command/InstallExtensionsForProjectCommandTest.php
  test/unit/Installing/InstallForPhpProject/InstallSelectedPackageTest.php
Labels: enhancement

#260 Updated list of supported extensions
  docs/supported-extensions.md
Labels: documentation
