Repository php/pie, pull requests merged in 2025-01, with the labels that each got.

#170 Remove ext-zip dependency
  composer.json
  composer.lock
  docs/usage.md
Labels: enhancement

#171 Ensure GithubPackageReleaseAssetsTest integration test uses GH token
  .github/workflows/continuous-integration.yml
  test/integration/Downloading/GithubPackageReleaseAssetsTest.php
Labels: bug

#173 Cleanup vendor after install
  src/ComposerIntegration/ComposerIntegrationHandler.php
  src/ComposerIntegration/PieComposerFactory.php
  src/ComposerIntegration/PiePackageInstaller.php
  src/ComposerIntegration/RemoveUnrelatedInstallOperations.php
  src/ComposerIntegration/VendorCleanup.php
  test/assets/vendor-cleanup-dir/autoload.php
  test/assets/vendor-cleanup-dir/composer/dummy
  test/assets/vendor-cleanup-dir/vendor1/dummy
  test/assets/vendor-cleanup-dir/vendor2/dummy
  test/unit/ComposerIntegration/RemoveUnrelatedInstallOperationsTest.php
  test/unit/ComposerIntegration/VendorCleanupTest.php
Labels: enhancement

#174 Fix access to the GITHUB_TOKEN
  .github/workflows/continuous-integration.yml
Labels: bug

#176 Add repository management commands
  .github/docs/Dockerfile
  .github/docs/templates/online.twig
  bin/pie
  docs/extension-maintainers.md
  docs/usage.md
  features/install-extensions.feature
  features/manage-repositories.feature
  src/Command/CommandHelper.php
  src/Command/RepositoryAddCommand.php
  src/Command/RepositoryListCommand.php
  src/Command/RepositoryRemoveCommand.php
  src/ComposerIntegration/ComposerIntegrationHandler.php
  src/ComposerIntegration/PieComposerFactory.php
  src/ComposerIntegration/PieJsonEditor.php
  src/Container.php
  test/behaviour/CliContext.php
  test/integration/Command/RepositoryManagementCommandsTest.php
  test/unit/Command/CommandHelperTest.php
  test/unit/ComposerIntegration/PieJsonEditorTest.php
Labels: enhancement

#178 Remove `php-standard-library/psalm-plugin`
  .github/workflows/continuous-integration.yml
  composer.json
  composer.lock
  psalm.xml.dist
Labels: enhancement

#179 Added PECL comparison
  docs/usage.md
Labels: documentation

#181 Update to Psalm 6.x
  .github/workflows/continuous-integration.yml
  composer.json
  composer.lock
  psalm.xml.dist
  src/Platform/TargetPhp/PhpizePath.php
Labels: enhancement

#180 Check the additional php.ini dir is writable
  src/Installing/Ini/StandardAdditionalPhpIniDirectory.php
  test/unit/Installing/Ini/StandardAdditionalPhpIniDirectoryTest.php
Labels: bug
