Repository php/pie, pull requests merged in 2025-03, with the labels that each got.

#195 `pie show` to only show PIE exts by default
  src/Command/ShowCommand.php
  test/integration/Command/ShowCommandTest.php
Labels: enhancement

#198 Fixing INI permissions issues
  src/File/FailedToCreateFile.php
  src/File/FailedToWriteFile.php
  src/File/SudoCreate.php
  src/File/SudoFilePut.php
  src/File/SudoUnlink.php
  src/Installing/Ini/OndrejPhpenmod.php
  src/Installing/Ini/StandardAdditionalPhpIniDirectory.php
  test/unit/File/SudoCreateTest.php
  test/unit/File/SudoFilePutTest.php
  test/unit/Installing/Ini/AddExtensionToTheIniFileTest.php
  test/unit/Installing/Ini/OndrejPhpenmodTest.php
Labels: bug

#200 VendorCleanup: fix missing `<` in `</comment>`
  src/ComposerIntegration/VendorCleanup.php
  test/unit/ComposerIntegration/VendorCleanupTest.php
Labels: bug

#201 composer-json-php-ext-schema.json: update `$id` to correct path
  resources/composer-json-php-ext-schema.json
Labels: enhancement

#199 Fix Windows reinstall/uninstall issue
  features/uninstall-extensions.feature
  src/Command/UninstallCommand.php
  src/Downloading/DownloadUrlMethod.php
  src/File/SudoCreate.php
  src/File/SudoUnlink.php
  src/File/WindowsDelete.php
  src/Installing/Ini/RemoveIniEntryWithFileGetContents.php
  src/Installing/WindowsInstall.php
Labels: bug

#202 Added PIE version banner to all commands
  bin/pie
Labels: enhancement

#203 Fix replace conflict bug
  src/ComposerIntegration/PhpBinaryPathBasedPlatformRepository.php
  src/ComposerIntegration/PieComposerInstaller.php
  src/ComposerIntegration/VersionSelectorFactory.php
  src/ExtensionName.php
  test/unit/ComposerIntegration/PhpBinaryPathBasedPlatformRepositoryTest.php
  test/unit/ComposerIntegration/VersionSelectorFactoryTest.php
  test/unit/DependencyResolver/ResolveDependencyWithComposerTest.php
Labels: bug

#206 Add section on the PIE build steps
  docs/extension-maintainers.md
Labels: documentation
