Repository php/pie, pull requests merged in 2025-09, with the labels that each got.

#346 Dep updates and bump composer versions
  .github/workflows/continuous-integration.yml
  composer.json
  composer.lock
  src/ComposerIntegration/BundledPhpExtensionsRepository.php
  test/install-bundled-php-exts.php
Labels: dependencies, php

#337 Ensure packages are filtered to match the extension name
  src/Installing/InstallForPhpProject/FindMatchingPackages.php
  test/unit/Installing/InstallForPhpProject/FindMatchingPackagesTest.php
Labels: enhancement

#350 De-duplicate docker image build for nightly and release tags
  .github/workflows/build-and-push-docker-image.yml
  .github/workflows/docker-nightly-image-push.yml
  .github/workflows/release.yml
Labels: enhancement

#357 Fix PIE using default PHP version for configure when invoking from a different PHP version
  .github/workflows/continuous-integration.yml
  src/Platform/TargetPhp/PhpBinaryPath.php
  test/behaviour/CliContext.php
  test/integration/Command/BuildCommandTest.php
  test/integration/Downloading/GithubPackageReleaseAssetsTest.php
  test/unit/Platform/TargetPhp/PhpBinaryPathTest.php
Labels: bug

#371 bitset and xattr are supported
  docs/supported-extensions.md
Labels: documentation

#373 Only suppress deprecations when running as Phar
  bin/pie
Labels: enhancement
