Repository php/pie, pull requests merged in 2025-07, with the labels that each got.

#276 273: Fix PHP warnings not being cleaned from output
  src/Platform/TargetPhp/PhpBinaryPath.php
  test/assets/valid-php-with-warnings.sh
  test/unit/Platform/TargetPhp/PhpBinaryPathTest.php
Labels: bug

#281 Regenerate composer.lock
  composer.lock
Labels: dependencies

#282 Run `composer validate --strict` as part of the Static Analysis CI
  .github/workflows/continuous-integration.yml
Labels: enhancement

#287 286: Trusted root update
  .github/workflows/check-outdated-trusted-root.yml
  resources/trusted-root.jsonl
Labels: enhancement
